config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]

  resources :cards do
    patch 'reveal_scores', on: :member
    patch 'hide_scores', on: :member
    resources :scores, only: [:create, :update, :destroy] # Nesting scores under cards
  end

  root "cards#index"
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    has_many :scores, dependent: :destroy
    has_many :cards, through: :scores
  
    def admin?
      self.admin
    end

    attribute :admin, :boolean, default: false
    validates :name, presence: true
    validates :email, presence: true, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Welcome to the app, #{@user.name}!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: "Account successfully deleted!"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def require_correct_user
    @user = User.find(params[:id])
    unless current_user == @user || current_user.admin?
      redirect_to root_url
    end
  end

  def require_signin
    unless current_user
      redirect_to new_session_url, alert: "Please sign in first!"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#create</h1>
  <p>Find me in app/views/users/create.html.erb</p>
</div>

app/views/users/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#destroy</h1>
  <p>Find me in app/views/users/destroy.html.erb</p>
</div>

app/views/users/edit.html.erb
<div class="form-container">
  <h1>Edit User</h1>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @user, local: true) do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-input" %>
    </div>

    <div>
      <%= form.label :email %>
      <%= form.email_field :email, class: "form-input" %>
    </div>

    <% if current_user.admin? %>
    <div class="checkbox-inline">
      <%= form.label :admin, 'Admin', class: 'inline-label' %>
      <%= form.check_box :admin %>
    </div>
    <% end %>

    <div>
      <%= form.label :password, "New Password" %>
      <%= form.password_field :password, class: "form-input" %>
    </div>

    <div>
      <%= form.label :password_confirmation, "Confirm New Password" %>
      <%= form.password_field :password_confirmation, class: "form-input" %>
    </div>

    <div>
      <%= form.submit "Save Changes", class: "button" %>
    </div>
  <% end %>

  <div>
    <%= link_to "Back", users_path %>
  </div>
</div>

app/views/users/index.html.erb
<div class="users-list">
  <% @users.each do |user| %>
    <div class="user-row">
      <div class="user-info">
        <%= link_to user.name, user_path(user), class: "user-name-link" %>
      </div>
      <div class="user-actions">
        <% if current_user && (current_user == user || current_user.admin?) %>
          <%= link_to 'Edit', edit_user_path(user), class: "button" %>
          <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: "button" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="form-container">
  <h1>Sign Up</h1>
  
  <%= form_with(model: @user, local: true) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-input" %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.email_field :email, class: "form-input" %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-input" %>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: "form-input" %>
    </div>

    <div class="form-group">
      <%= form.submit "Sign Up", class: "form-button" %>
    </div>
  <% end %>

  <div class="signup-link">
    <%= link_to 'Sign In', new_session_path, class: "signup-button" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user">
  <h1 class="user-name"><%= @user.name %></h1>
  <p class="user-email"><%= @user.email %></p>
  
  <div class="actions">
    <% if current_user == @user || current_user.admin? %>
      <%= link_to 'Edit', edit_user_path(@user), class: 'button edit' %> 
      <%= link_to 'Delete', @user, method: :delete, data: { confirm: "Are you sure you want to delete this account?" }, class: 'button delete' %> 
      <%= link_to 'Sign Out', session_path, method: :delete, class: 'signup-link' %>
    <% end %>
  </div>
</div>

app/views/users/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#update</h1>
  <p>Find me in app/views/users/update.html.erb</p>
</div>